server:
  port: 8080
  servlet:
    context-path: /sqlReserve

#\u6307\u5B9Afreemarker\u7684\u6A21\u677F\u8DEF\u5F84\u3001\u6A21\u677F\u7684\u540E\u7F00\u3001\u6307\u5B9A\u5B57\u7B26\u96C6
spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/webapp/
    charset: utf-8
    cache: false #\u662F\u5426\u8981\u542F\u7528\u7F13\u5B58
    expose-request-attributes: true #\u66B4\u9732\u8BF7\u6C42
    expose-session-attributes: true #\u4F1A\u8BDD\u5C5E\u6027
  web:
    resources:
      static-locations: classpath:/static/ #\u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
#  jpa:
#    database-platform: org.hibernate.dialect.SQLiteDialect
#    hibernate:
#      ddl-auto: validate

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/main/resources/generate.db

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # \u5168\u5C40\u903B\u8F91\u5220\u9664\u7684\u5B9E\u4F53\u5B57\u6BB5\u540D
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C\uFF08\u9ED8\u8BA4\u4E3A 1\uFF09
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C\uFF08\u9ED8\u8BA4\u4E3A 0\uFF09
